Auth
Chigil/computer_shop pull request #2
Opened 2022-04-12 13:39 UTC by Chigil

2022-04-12 15:18 UTC, BlackImpulse requested changes

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/auth.module.ts
> +      secret: process.env.PRIVATE_KEY,
А если его не будет?

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/auth.service.ts
> +        'User witch this email busy',
User with this email already exists
А у тебя получается, что пользователь занят

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/auth.service.ts
> +        'User witch this email busy',
По-хорошему можно для этого дела сделать отдельный exception.
NotUniqueValue, например

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/auth.service.ts
> +  }
Отступ между методами

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/dto/jwt-token.dto.ts
> +  role: Role;
А валидация роли?

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/strategies/auth.jwt.strategy.ts
> +      secretOrKey: process.env.PRIVATE_KEY,
А если не будет?

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/strategies/auth.jwt.strategy.ts
> +    validateUser.id = payload.id
plainToClass?

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/auth/strategies/auth.jwt.strategy.ts
> +    return { email: payload.email, id: payload.id, role: payload.role };
Не понял смысла этого return-а

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/user/user.controller.ts
> +  @Public()
Раз уж оставили auth модуль, то этот метод не должен быть публичным

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/user/user.controller.ts
> +  @Public()
Этот вообще публичным не должен быть

2022-04-12 15:18 UTC, BlackImpulse commented on apps/computer-shop/src/user/user.service.ts
> +      await user.$set('role', role.id); // create TRIGGER
Комментарий остался

2022-04-13 07:00 UTC, Chigil commented on apps/computer-shop/src/auth/strategies/auth.jwt.strategy.ts
> +    return { email: payload.email, id: payload.id, role: payload.role };
Это для случая регистрации

2022-04-14 06:28 UTC, merged