Feature/itx5 other 492 pdf saver
Chigil/computer_shop pull request #9
Opened 2022-05-02 11:02 UTC by Chigil

2022-05-02 11:06 UTC, Chigil commented on apps/computer-shop/src/order/order.service.ts
> +    const response = await this.amqpConnection.request<PdfResponseContract>({
Тут у меня ругается, возможно это контракт его не устраивает!

2022-05-02 11:11 UTC, Chigil commented on apps/computer-shop/src/order/order.service.ts
> +    return this.orderPublisher.requestOrderPdf(data);
И тут моментик

2022-05-05 13:05 UTC, BlackImpulse requested changes

2022-05-05 13:05 UTC, BlackImpulse commented on apps/computer-shop/src/order/order.service.ts
> +        '1ae303b2-efe5-4e12-9db9-10cdb96a9567',
А если id поменяется?

2022-05-05 13:05 UTC, BlackImpulse commented on libs/common/src/rabbit-config/rabbit-config.ts
> +    uri: 'amqp://guest:guest@localhost:5672',
Это должно быть в .env

2022-05-06 07:07 UTC, merged